github pages

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -53,8 +53,19 @@ jobs:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./site
 
+    - name: Confirm version
+      run: |
+        echo "Package version: ${{ github.event.release.tag_name }}"
 
-    # Compiling the Python package
+    - name: Validate version format
+      run: |
+        if [[ ! "${{ github.event.release.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+          echo "Error: Tag name is not in the correct format (vX.X.X)."
+          exit 1
+        fi
+      
+
+      # Compiling the Python package
     - name: Build package
       run: |
         python -m pip install --upgrade build twine
@@ -64,12 +75,15 @@ jobs:
     - name: Install Twine
       run: pdm add --dev twine
 
+
+
     # Publish package to TestPyPI using Twine
     # Here we use my credentials
     - name: Publish package to TestPyPI
       env:
 
-        TWINE_USERNAME: '__token__'  # TestPyPI user
-        TWINE_PASSWORD: 'pypi-AgENdGVzdC5weXBpLm9yZwIkOWJkYTg2NzAtZjI2Ni00NzM5LTk5ZjYtMDE5MGQ5Y2E0YzgwAAISWzEsWyJjYXBvLXRvb2xzIl1dAAIsWzIsWyJiMjVkOTQ0My01ODc5LTRiYWMtYTE3Yi1jNWVmZmUyYmFjNzYiXV0AAAYgulX7v0XPB2L-kf5bpRwCTqriIvyfuiGiYb3VI9zrOQ4'  # TestPyPI password
+        TWINE_USERNAME: __token__  # TestPyPI user
+        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # TestPyPI password
       run: |
         twine upload --repository-url https://test.pypi.org/legacy/ --verbose dist/* # Upload the files to TestPyPI
+
